### ISSUE TITLE
Allow loading exec code from file

### ISSUE THREAD

**Issue by ritave** [dapphub/hevm#16]
I'm using hsevm to test my own manually written assembly and copy-pasting the bytecode manually into cli is cumbersome. `-o` option to load the file directly instead of `--code` would be useful.

**Comment by mbrock** [comment]
Agreed, that would be a good feature. With hand-written assembly, though, you should be able to use shell interpolation to get the bytecode in there, like:

    hsevm --code $(cat foo.evm) ...

(That only wouldn't work with huge EVM files that exceed the shell argv limits...)

By the way, please beware of possible consensus bugs in hsevm. It's useful for debugging, but until we thoroughly pass the Foundation's test suite, we can't claim to implement consensus Ethereum semantics -- so your final testing should be done with another implementation. Getting hsevm into verifiable consensus with Metropolis is a top priority for me right now, but it'll still take a while.
